std = 'lua51'
self = false
globals = {
    window = {
        fields = {
            "left",
            "right",
            "bottom",
            "top",
            "width",
            "height",
            "pixel_width",
            "pixel_height",
            "mode",
            "clear_color",
            "stencil_clear_value",
            "letterbox",
            "lock_pointer",
            "show_cursor",
            "scene",
            "projection",
            "close",
            "resized",
            "key_down",
            "keys_down",
            "key_pressed",
            "keys_pressed",
            "key_released",
            "keys_released",
            "mouse_position",
            "mouse_norm_position",
            "mouse_pixel_position",
            "mouse_delta",
            "mouse_norm_delta",
            "mouse_pixel_delta",
            "mouse_down",
            "mouse_pressed",
            "mouse_released",
            "mouse_wheel",
            "mouse_wheel_delta",
            "touches_began",
            "touches_ended",
            "active_touches",
            "touch_began",
            "touch_ended",
            "touch_active",
            "touch_position",
            "touch_norm_position",
            "touch_pixel_position",
            "touch_delta",
            "touch_norm_delta",
            "touch_pixel_delta",
            "touch_force",
            "touch_force_available",
        }
    }
}

read_globals = {
    am = {
        fields = {
            "controller_button_released",
            "version",
            "parallel",
            "delta_time",
            "line",
            "ubyte_array",
            "ushort_norm_array",
            "audio_buffer",
            "init_gamecenter",
            "float_array",
            "translate",
            "cull_sphere",
            "perf_stats",
            "decode_png",
            "struct_array",
            "submit_gamecenter_score",
            "load_audio",
            "language",
            "controllers_attached",
            "sprite",
            "controller_button_down",
            "vec4_array",
            "short_array",
            "controller_rstick_pos",
            "byte_norm_array",
            "base64_decode",
            "short_norm_array",
            "eval_js",
            "series",
            "controller_attached",
            "sfxr_synth",
            "controller_rt_val",
            "framebuffer",
            "controller_lstick_pos",
            "load_script",
            "circle",
            "uint_norm_array",
            "depth_test",
            "bind",
            "uint_array",
            "ushort_elem_array",
            "vec2_array",
            "billboard",
            "use_program",
            "to_json",
            "loop",
            "frame_time",
            "group",
            "current_time",
            "texture2d",
            "controller_present",
            "quads",
            "encode_png",
            "load_image",
            "load_buffer",
            "particles2d",
            "buffer",
            "program",
            "image_buffer",
            "load_bitmap_font",
            "wrap",
            "load_string",
            "postprocess",
            "read_uniform",
            "window",
            "lookat",
            "show_gamecenter_leaderboard",
            "viewport",
            "platform",
            "cull_face",
            "color_mask",
            "text",
            "draw",
            "rect",
            "gamecenter_available",
            "load_obj",
            "rotate",
            "glob",
            "controller_button_pressed",
            "scale",
            "transform",
            "blend",
            "int_norm_array",
            "int_array",
            "byte_array",
            "ushort_array",
            "stencil_test",
            "controllers_present",
            "ubyte_norm_array",
            "parse_json",
            "controller_lt_val",
            "controller_detached",
            "base64_encode",
            "controllers_detached",
            "delay",
            "vec3_array",
            "tween",
            "wait",
            "uint_elem_array",
            "submit_gamecenter_achievement",
        },
    },
    math = {
        fields = {
            "oblique",
            "perspective",
            "fract",
            "scale4",
            "slerp",
            "distance",
            "randvec3",
            "simplex",
            "mix",
            "perlin",
            "dot",
            "lookat",
            "randvec4",
            "rotate4",
            "translate4",
            "ortho",
            "cross",
            "inverse",
            "sign",
            "length",
            "clamp",
            "randvec2",
            "normalize",
        },
    },
    table = {
        fields = {
            "merge",
            "keys",
            "append",
            "remove_all",
            "search",
            "filter",
            "shuffle",
            "tostring",
            "values",
            "deep_copy",
            "count",
            "clear",
            "shallow_copy",
        },
    },
    window = {
        fields = {
            scene = {
                fields = {
                    "child",
                    "prepend",
                    "untag",
                    "replace",
                    "action",
                    "hidden",
                    "child_pairs",
                    "remove_all",
                    "all",
                    "num_children",
                    "recursion_limit",
                    "remove",
                    "tag",
                    "late_action",
                    "append",
                    "cancel",
                    "paused",
                },
            },
            [1] = "clear_color",
            [2] = "touch_ended",
            [3] = "left",
            [4] = "lock_pointer",
            [5] = "keys_pressed",
            [6] = "touch_norm_delta",
            [7] = "touch_force",
            [8] = "bottom",
            [9] = "touch_began",
            [10] = "mouse_down",
            [11] = "mouse_norm_delta",
            [12] = "mouse_pressed",
            [13] = "touch_force_available",
            [14] = "touch_active",
            [15] = "mouse_norm_position",
            [16] = "keys_released",
            [17] = "right",
            [18] = "pixel_height",
            [19] = "show_cursor",
            [20] = "top",
            [21] = "stencil_clear_value",
            [22] = "resized",
            [23] = "touch_pixel_delta",
            [24] = "mouse_wheel_delta",
            [25] = "pixel_width",
            [26] = "touch_delta",
            [27] = "touch_pixel_position",
            [28] = "key_released",
            [29] = "mouse_released",
            [30] = "projection",
            [31] = "touches_began",
            [32] = "key_pressed",
            [33] = "touch_norm_position",
            [34] = "touch_position",
            [35] = "mouse_pixel_delta",
            [36] = "active_touches",
            [37] = "close",
            [38] = "height",
            [39] = "mouse_wheel",
            [40] = "letterbox",
            [41] = "key_down",
            [42] = "mouse_pixel_position",
            [43] = "mouse_delta",
            [44] = "touches_ended",
            [45] = "width",
            [46] = "mode",
            [47] = "keys_down",
            [48] = "mouse_position",
        },
    },
    [1] = "vec4",
    [2] = "quat",
    [3] = "mat4",
    [4] = "noglobals",
    [5] = "vec3",
    [6] = "log",
    [7] = "mat2",
    [8] = "following easing functions are pre-defined ",
    [9] = "mat3",
    [10] = "vec2",
}
files["src/conf.lua"] = {
    globals = {
        "title",
        "shortname",
        "author",
        "appid",
        "version",
        "support_email",
        "display_name",
        "dev_region",
        "supported_languages",
        "icon",
        "launch_image",
        "orientation"
    }
}