std = 'lua51'
self = true
globals = {
    window = {
        fields = {
            "left",
            "right",
            "bottom",
            "top",
            "width",
            "height",
            "pixel_width",
            "pixel_height",
            "mode",
            "clear_color",
            "stencil_clear_value",
            "letterbox",
            "lock_pointer",
            "show_cursor",
            "scene",
            "projection",
        }
    }
}

read_globals = {
    am = {
        fields = {
            "controller_button_released",
            "version",
            "parallel",
            "delta_time",
            "line",
            "ubyte_array",
            "ushort_norm_array",
            "audio_buffer",
            "init_gamecenter",
            "float_array",
            "translate",
            "cull_sphere",
            "perf_stats",
            "decode_png",
            "struct_array",
            "submit_gamecenter_score",
            "load_audio",
            "language",
            "controllers_attached",
            "sprite",
            "controller_button_down",
            "vec4_array",
            "short_array",
            "controller_rstick_pos",
            "byte_norm_array",
            "base64_decode",
            "short_norm_array",
            "eval_js",
            "series",
            "controller_attached",
            "sfxr_synth",
            "controller_rt_val",
            "framebuffer",
            "controller_lstick_pos",
            "load_script",
            "circle",
            "uint_norm_array",
            "depth_test",
            "bind",
            "uint_array",
            "ushort_elem_array",
            "vec2_array",
            "billboard",
            "use_program",
            "to_json",
            "loop",
            "frame_time",
            "group",
            "current_time",
            "texture2d",
            "controller_present",
            "quads",
            "encode_png",
            "load_image",
            "load_buffer",
            "particles2d",
            "buffer",
            "program",
            "image_buffer",
            "load_bitmap_font",
            "wrap",
            "load_string",
            "postprocess",
            "read_uniform",
            "window",
            "lookat",
            "show_gamecenter_leaderboard",
            "viewport",
            "platform",
            "cull_face",
            "color_mask",
            "text",
            "draw",
            "rect",
            "gamecenter_available",
            "load_obj",
            "rotate",
            "glob",
            "controller_button_pressed",
            "scale",
            "transform",
            "blend",
            "int_norm_array",
            "int_array",
            "byte_array",
            "ushort_array",
            "stencil_test",
            "controllers_present",
            "ubyte_norm_array",
            "parse_json",
            "controller_lt_val",
            "controller_detached",
            "base64_encode",
            "controllers_detached",
            "delay",
            "vec3_array",
            "tween",
            "wait",
            "uint_elem_array",
            "submit_gamecenter_achievement",
        },
    },
    math = {
        fields = {
            "oblique",
            "perspective",
            "fract",
            "scale4",
            "slerp",
            "distance",
            "randvec3",
            "simplex",
            "mix",
            "perlin",
            "dot",
            "lookat",
            "randvec4",
            "rotate4",
            "translate4",
            "ortho",
            "cross",
            "inverse",
            "sign",
            "length",
            "clamp",
            "randvec2",
            "normalize",
        },
    },
    table = {
        fields = {
            "merge",
            "keys",
            "append",
            "remove_all",
            "search",
            "filter",
            "shuffle",
            "tostring",
            "values",
            "deep_copy",
            "count",
            "clear",
            "shallow_copy",
        },
    },
    [1] = "vec4",
    [2] = "quat",
    [3] = "mat4",
    [4] = "mat3",
    [5] = "noglobals",
    [6] = "mat2",
    [7] = "log",
    [8] = "vec2",
    [9] = "following easing functions are pre-defined ",
    [10] = "vec3",
}
files["src/conf.lua"] = {
    globals = {
        "title",
        "shortname",
        "author",
        "appid",
        "version",
        "support_email",
        "display_name",
        "dev_region",
        "supported_languages",
        "icon",
        "launch_image",
        "orientation"
    }
}